{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: kubetime-secrets
  labels:
    {{- include "kubetime.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additional }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
