apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetime.fullname" . }}
  labels:
    {{- include "kubetime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubetime.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
