# Production values for kubetime
# This file contains production-specific overrides for the kubetime Helm chart

replicaCount: 2

image:
  repository: ghcr.io/hackclub/kubetime/hackatime
  pullPolicy: IfNotPresent
  tag: "latest"

worker:
  image:
    repository: ghcr.io/hackclub/kubetime/hackatime-worker
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: kubetime.hackclub.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kubetime-tls
      hosts:
        - kubetime.hackclub.com

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

worker:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Environment variables - these should be set via secrets in production
env:
  # Database configuration
  DATABASE_URL: ""
  POOL_DATABASE_URL: ""
  SAILORS_LOG_DATABASE_URL: ""
  WAKATIME_DATABASE_URL: ""
  WAREHOUSE_DATABASE_URL: ""
  
  # Encryption keys
  ENCRYPTION_DETERMINISTIC_KEY: ""
  ENCRYPTION_KEY_DERIVATION_SALT: ""
  ENCRYPTION_PRIMARY_KEY: ""
  SECRET_KEY_BASE: ""
  PREFIXED_IDS_SALT: ""
  
  # Rails configuration
  RAILS_MASTER_KEY: ""
  RAILS_MAX_THREADS: "10"
  RAILS_ENV: "production"
  
  # GitHub OAuth
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  
  # Slack integration
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SLACK_SIGNING_SECRET: ""
  SLACK_USER_OAUTH_TOKEN: ""
  SAILORS_LOG_SLACK_BOT_OAUTH_TOKEN: ""
  SAILORS_LOG_SLACK_SIGNING_SECRET: ""
  
  # Airtable integration
  ADDRESS_AIRTABLE_PAT: ""
  LOOPS_AIRTABLE_PAT: ""
  NEIGHBORHOOD_AIRTABLE_PAT: ""
  
  # External services
  HACKCLUB_GEOCODER_API_KEY: ""
  IPINFO_API_KEY: ""
  LOOPS_API_KEY: ""
  MAIL_HACKCLUB_TOKEN: ""
  STATS_API_KEY: ""
  TELETYPE_API_KEY: ""
  
  # Internal API
  INTERNAL_API_KEYS: ""
  
  # Security
  RACK_ATTACK_BYPASS: ""
  
  # Monitoring
  SENTRY_DSN: ""
  
  # SMTP configuration
  SMTP_ADDRESS: ""
  SMTP_PASSWORD: ""
  SMTP_PORT: "587"
  SMTP_USER_NAME: ""
  
  # Application settings
  WEB_CONCURRENCY: "10"

# Secrets configuration
secrets:
  create: true
  additional: {}

# ConfigMaps for non-sensitive configuration
configMaps:
  create: true
  additional: {}
